name: deep_lp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.10.0=pyhe01879c_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39h0802e32_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - bottleneck=1.4.2=py39hc99e966_0
  - brotli-python=1.1.0=py39ha51f57c_3
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.9.9=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.2.1=py39h214f63a_1
  - cpython=3.9.23=py39hd8ed1ab_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py39h1f3cc84_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - fonttools=4.59.2=py39h02ab6af_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6c2663c_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2025.2.0=h57928b3_757
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39hcbf5309_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=12.15=h906ac69_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.1=h550210a_0
  - libuv=1.51.0=hfd05255_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2023.1.0=h6a75c08_48682
  - mkl-service=2.4.0=py39h827c3e9_2
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=2.0.2=py39h60232e0_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py39ha5e6156_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py39hfa8c767_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py39ha55e580_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=6.7.1=py39h5da7b33_0
  - pyqt6-sip=13.9.1=py39h827c3e9_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.23=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=8_cp39
  - pytorch=2.5.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py39h5fb4b08_0
  - pywinpty=2.0.15=py39ha51f57c_0
  - pyyaml=6.0.2=py39hf73967f_2
  - pyzmq=27.0.2=py39h248659b_0
  - qtbase=6.7.2=h0804d20_0
  - qtdeclarative=6.7.2=h5da7b33_0
  - qtsvg=6.7.2=hf2fb9eb_0
  - qttools=6.7.2=h0de5f00_0
  - qtwebchannel=6.7.2=h5da7b33_0
  - qtwebsockets=6.7.2=h5da7b33_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.0=py39hcab59ba_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py39h5da7b33_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h18a62a1_3
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhe01879c_2
  - torchvision=0.20.1=py39_cpu
  - tornado=6.5.2=py39h0802e32_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=15.1.0=py39h827c3e9_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.23.0=py39h0802e32_3
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\olduh\anaconda3\envs\deep_lp
